version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: FlaskDockerfile
    container_name: LibraryBouncerApp
    command: gunicorn -w 3 -b :8000 app
    volumes:
      - ./access_stats.txt:/code/access_stats.txt
    networks:
      - network
    restart:
      always

  nginx:
    image: nginx:latest
    container_name: LibraryBouncerNginx
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8000:80
    depends_on:
      - app
    networks:
      - network
    restart:
      always

networks:
  network:
    driver: bridge
